export default [
  {
    id: 'chantier',
    type: 'polygon',
    label: 'Elément de chantier',
    img: '../statics/chantier.png',
    isNotSelected: false,
  },
  {
    id: 'garbage',
    type: 'polygon',
    label: 'Poubelle',
    img: '../statics/poubelles.jpg',
    isNotSelected: false,
  },
  {
    id: 'stairs',
    type: 'polygon',
    label: 'Escalier',
    img: '../statics/stairs.png',
    isNotSelected: false,
  },
  {
    id: 'crosswalk',
    type: 'polygon',
    label: 'Passage piéton',
    img: '../statics/pieton.png',
    isNotSelected: false,
  },
  {
    id: 'tactiletap',
    type: 'polygon',
    label: 'Bandes podotaciles',
    img: '../statics/podotactile.jpg',
    isNotSelected: false,
  },
  {
    id: 'poteauxpassagepieton',
    type: 'polygon',
    label: 'Poteaux',
    img: '../statics/poteaux.png',
    isNotSelected: false,
  },
  {
    id: 'parkingpmr',
    type: 'polygon',
    label: 'Place de parking PMR',
    img: '../statics/parkingpmr.jpg',
    isNotSelected: false,
  },
  {
    id: 'cobblestone',
    type: 'polygon',
    label: 'Pavés',
    img: '../statics/pave.png',
    isNotSelected: false,
  },
  // {
  //   id: 'bev',
  //   type: 'polygon',
  //   label: 'Bande d\'éveil vigilance',
  //   img: '../statics/bev.png',
  //   isNotSelected: false,
  // },
  {
    id: 'none',
    type: 'polygon',
    label: 'Aucun',
  },
];
